<?xml version="1.0"?>
<robot name="NextageAOpen"
       xmlns:xi="http://www.w3.org/2001/xinclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
       xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find nextagea_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find nextagea_description)/urdf/common.xacro" />

  <xacro:include filename="$(find nextagea_description)/urdf/NextageA_base.xacro" />
  <xacro:include filename="$(find nextagea_description)/urdf/NextageA_robot.xacro" />
  <xacro:include filename="$(find nextagea_description)/urdf/nxao_gz_camera.xacro" />

  <xacro:arg name="use_hand_cameras" default="false"/>
  <xacro:arg name="use_ft_sensors" default="false"/>

  <xacro:macro name="nxao_camera" params="prefix parent">
    <xacro:if value="${prefix == 'L'}">
      <xacro:property name="m" value="+1.0" />
    </xacro:if>

    <xacro:if value="${prefix == 'R'}">
      <xacro:property name="m" value="-1.0" />
    </xacro:if>

    <xacro:gazebo_nx_link name="${prefix}ARM_camera_Link" color="Black" />
    <link name="${prefix}ARM_camera_Link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://nextagea_description/urdf/meshes/${prefix}_CAM.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.025" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.037"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.0525 ${(float(m)) * 0.029} -0.02" rpy="0 0 0"/>
        <geometry>
          <box size="0.057 0.106 0.042"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.05156" />
        <origin xyz="0.0 0.0 -0.08" rpy="0 -0 0"/>
        <inertia ixx="0.00194072" ixy="${float(m) * 1.1e-07}" ixz="-0.00042482" iyy="0.00209392" iyz="${float(m) * 1.2e-07}" izz="0.00035788"/>
      </inertial>
    </link>

    <joint name="${prefix}ARM_JOINT6" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}ARM_camera_Link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <xacro:camera_joint_link_gzplugin
      camera_name="CAMERA_HAND_${prefix}" link_parent="${parent}"
      jnt_displacement_x="${jnt_hand_camera_displacement_x}"
      jnt_displacement_y="${float(m) * jnt_hand_camera_displacement_y}"
      jnt_displacement_z="${jnt_hand_camera_displacement_z}"
      jnt_rotation_x="0" jnt_rotation_y="${jnt_hand_camera_rot_y}" jnt_rotation_z="0"
      link_displacement_x="0.0325" link_displacement_y="0" link_displacement_z="0"
      link_rotation_x="0" link_rotation_y="${M_PI/2}" link_rotation_z="-${link_hand_camera_rot_z}" />
  </xacro:macro>

  <xacro:macro name="nxao_ft_sensor" params="prefix parent">
    <xacro:if value="${prefix == 'L'}">
      <xacro:property name="m" value="+1" />
    </xacro:if>

    <xacro:if value="${prefix == 'R'}">
      <xacro:property name="m" value="-1" />
    </xacro:if>

    <xacro:gazebo_nx_link name="${prefix}ARM_ft_Link" color="LightGrey" />
    <link name="${prefix}ARM_ft_Link">
      <visual>
        <origin xyz="0 0 0.0185" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.037" radius="0.035"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.6 0.6 0.6 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.0185" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.037" radius="0.04"/>
        </geometry>
      </collision>
      <!-- TODO: The inertial values are copied from ARM_JOINT5_Link. Replace with proper values. -->
      <inertial>
        <mass value="1.05156" />
        <origin xyz="0.0 0.0 -0.08" rpy="0 -0 0"/>
        <inertia ixx="0.00194072" ixy="1.1e-07" ixz="-0.00042482" iyy="0.00209392" iyz="1.2e-07" izz="0.00035788"/>
      </inertial>
    </link>

    <joint name="${prefix}ARM_ft_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}ARM_ft_Link"/>
      <origin xyz="0 0 -0.037" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
  </xacro:macro>

  <xacro:property name="arm_tip" value="ARM_JOINT5_Link" />

  <xacro:if value="$(arg use_ft_sensors)">
    <xacro:nxao_ft_sensor prefix="L" parent="L${arm_tip}" />
    <xacro:nxao_ft_sensor prefix="R" parent="R${arm_tip}" />
    <xacro:property name="arm_tip" value="ARM_ft_Link" />
  </xacro:if>

  <xacro:if value="$(arg use_hand_cameras)">
    <xacro:nxao_camera prefix="L" parent="L${arm_tip}" />
    <xacro:nxao_camera prefix="R" parent="R${arm_tip}" />
    <xacro:property name="arm_tip" value="ARM_camera_Link" />
  </xacro:if>

</robot>
